# Generated by Django 4.2.30 on 2026-04-21 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('main_worker', 'Main Worker'), ('helper', 'Helper'), ('driver', 'Driver'), ('accountant', 'Accountant')], max_length=20)),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('address', models.TextField()),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
