# Generated by Django 4.2.30 on 2026-04-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('main_worker', 'Main Worker'), ('helper', 'Helper'), ('driver', 'Driver'), ('storage_manager', 'Storage Manager'), ('accountant', 'Accountant')], max_length=20),
        ),
    ]
