# Generated by Django 4.2.30 on 2026-04-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('main_worker', 'Main Worker'), ('helper', 'Helper'), ('driver', 'Driver'), ('storage_manager', 'Storage Manager'), ('office_staff', 'Office Staff')], max_length=20),
        ),
    ]
