# Generated by Django 4.2.30 on 2026-04-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('main_worker', 'Main Worker'), ('helper', 'Helper'), ('driver', 'Driver'), ('client', 'Client')], default='helper', max_length=20),
        ),
    ]
