# Generated by Django 4.2.30 on 2026-04-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('office_staff', 'Office Staff'), ('main_worker', 'Main Worker'), ('helper', 'Helper'), ('driver', 'Driver'), ('storage_manager', 'Storage Manager'), ('client', 'Client')], default='helper', max_length=20),
        ),
    ]
