# Generated by Django 6.0.4 on 2026-05-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0002_workarea_worksite_client_email_worksite_client_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
