# Generated by Django 6.0.4 on 2026-05-03 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0003_worksite_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksite',
            name='amount_paid',
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque')], default='bank_transfer', max_length=50)),
                ('reference_id', models.CharField(blank=True, help_text='Transaction ID or Cheque Number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payments', to='sites_mgmt.worksite')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
