# Generated by Django 6.0.4 on 2026-05-09 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0005_sitepayment_delete_clientpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAreaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_comments', to=settings.AUTH_USER_MODEL)),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sites_mgmt.workarea')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
