# Generated by Django 4.2.30 on 2026-04-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_materialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='custom_item_name',
            field=models.CharField(blank=True, help_text='Used if item is not in catalog', max_length=200),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
