# Generated by Django 4.2.30 on 2026-04-26 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0002_workarea_worksite_client_email_worksite_client_user_and_more'),
        ('employees', '0003_alter_employee_role'),
        ('inventory', '0003_materialrequest_custom_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='employees.employee')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_received', to='sites_mgmt.worksite')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit (visible only to admin/managers)', max_digits=10),
        ),
        migrations.CreateModel(
            name='DeliveryLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.deliverylog')),
            ],
        ),
    ]
