# Generated by Django 4.2.30 on 2026-04-26 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_deliverylog_item_unit_price_deliverylogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='source_storage',
            field=models.ForeignKey(blank=True, help_text='Where did you pick up these items?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_sent', to='inventory.storagefacility'),
        ),
    ]
