# Generated by Django 6.0.4 on 2026-04-29 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_materialrequest_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('Bags', 'Bags'), ('Pieces', 'Pieces'), ('SqFt', 'SqFt'), ('SqM', 'SqM'), ('Kg', 'Kg'), ('Litre', 'Litre'), ('Bundle', 'Bundle'), ('Box', 'Box'), ('Pack', 'Pack'), ('Roll', 'Roll'), ('Set', 'Set'), ('Feet', 'Feet'), ('Metre', 'Metre'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitestock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storagestock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
