# Generated by Django 4.2.30 on 2026-04-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarysummary',
            options={'ordering': ['-end_date', '-year', '-month']},
        ),
        migrations.AlterUniqueTogether(
            name='salarysummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salarysummary',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarysummary',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarysummary',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarysummary',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
