# Generated by Django 4.2.30 on 2026-04-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_advancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='salary_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deducted_advances', to='salary.salarysummary'),
        ),
    ]
