# Generated by Django 6.0.4 on 2026-04-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_advancerequest_salary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by admin. If blank, full amount is assumed.', max_digits=10, null=True),
        ),
    ]
