# Generated by Django 4.2.30 on 2026-04-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('1_5_days', '1.5 Days'), ('holiday', 'Holiday'), ('leave', 'Leave')], default='present', max_length=10),
        ),
    ]
